### ISSUE TITLE
Misspelling of "Papaya" in WOOD.java

### ISSUE THREAD

**Issue by Tanimodori** [Qwertygiy/qwertech#1]
https://github.com/Qwertygiy/qwertech/blob/21c06d074fe71957b1e2fead58845f6e43efaf2b/src/main/java/com/kbi/qwertech/api/data/WOOD.java#L66

**Comment by Qwertygiy** [comment]
Whoops, copy-paste error there. Paduak is a completely different type of wood. Will update.
